window.NICKEL_SITES = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [121.35, -2.55] },
      "properties": {
        "id": "sorowako",
        "name": "Sorowako",
        "province": "Sulawesi Selatan",
        "type": "Laterite",
        "context": "East Sulawesi Ophiolite Belt",
        "tier": "HIGH",
        "elevation_mean": 450,
        "elevation_max": 600,
        "elevation_min": 380,
        "slope_mean": 12,
        "roughness": 15,
        "terrain_class": "HILLY",
        "safety_score": 75,
        "safety_risks": "Moderate slope, good access",
        "prob_score": 95,
        "prob_conf": "High (Operating Mine)",
        "worth_score": 90,
        "worth_est": "Rp 150M",
        "recommendation": "GO"
      }
    },
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [121.96, -2.82] },
      "properties": {
        "id": "morowali",
        "name": "Morowali (IMIP)",
        "province": "Sulawesi Tengah",
        "type": "Laterite",
        "context": "East Sulawesi Ophiolite Belt",
        "tier": "HIGH",
        "elevation_mean": 200,
        "elevation_max": 400,
        "elevation_min": 50,
        "slope_mean": 8,
        "roughness": 10,
        "terrain_class": "ROLLING",
        "safety_score": 85,
        "safety_risks": "Low slope, excellent infrastructure",
        "prob_score": 90,
        "prob_conf": "High",
        "worth_score": 98,
        "worth_est": "Rp 50M",
        "recommendation": "GO"
      }
    },
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [127.95, 0.47] },
      "properties": {
        "id": "weda_bay",
        "name": "Weda Bay",
        "province": "Maluku Utara",
        "type": "Laterite",
        "context": "Halmahera Ophiolite",
        "tier": "HIGH",
        "elevation_mean": 300,
        "elevation_max": 800,
        "elevation_min": 20,
        "slope_mean": 18,
        "roughness": 25,
        "terrain_class": "MOUNTAINOUS",
        "safety_score": 60,
        "safety_risks": "Steep terrain, dense forest",
        "prob_score": 95,
        "prob_conf": "High",
        "worth_score": 85,
        "worth_est": "Rp 250M",
        "recommendation": "CONDITIONAL"
      }
    },
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [121.61, -4.18] },
      "properties": {
        "id": "pomalaa",
        "name": "Pomalaa",
        "province": "Sulawesi Tenggara",
        "type": "Laterite",
        "context": "Southeast Sulawesi Ophiolite",
        "tier": "MEDIUM",
        "elevation_mean": 150,
        "elevation_max": 300,
        "elevation_min": 10,
        "slope_mean": 6,
        "roughness": 8,
        "terrain_class": "FLAT",
        "safety_score": 90,
        "safety_risks": "Very accessible",
        "prob_score": 80,
        "prob_conf": "Medium",
        "worth_score": 88,
        "worth_est": "Rp 80M",
        "recommendation": "GO"
      }
    },
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [129.88, -0.07] },
      "properties": {
        "id": "gag_island",
        "name": "Gag Island",
        "province": "Papua Barat Daya",
        "type": "Laterite",
        "context": "Waigeo Ophiolite",
        "tier": "HIGH",
        "elevation_mean": 120,
        "elevation_max": 250,
        "elevation_min": 0,
        "slope_mean": 10,
        "roughness": 12,
        "terrain_class": "ROLLING",
        "safety_score": 65,
        "safety_risks": "Remote island logistics",
        "prob_score": 85,
        "prob_conf": "Medium",
        "worth_score": 75,
        "worth_est": "Rp 300M",
        "recommendation": "CONDITIONAL"
      }
    },
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [127.71, -1.55] },
      "properties": {
        "id": "obi_island",
        "name": "Obi Island",
        "province": "Maluku Utara",
        "type": "Laterite",
        "context": "Obi Ophiolite",
        "tier": "HIGH",
        "elevation_mean": 400,
        "elevation_max": 900,
        "elevation_min": 0,
        "slope_mean": 20,
        "roughness": 30,
        "terrain_class": "MOUNTAINOUS",
        "safety_score": 55,
        "safety_risks": "Very steep, remote",
        "prob_score": 90,
        "prob_conf": "High",
        "worth_score": 80,
        "worth_est": "Rp 280M",
        "recommendation": "CONDITIONAL"
      }
    },
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [122.11, -3.83] },
      "properties": {
        "id": "konawe",
        "name": "Konawe",
        "province": "Sulawesi Tenggara",
        "type": "Laterite",
        "context": "Southeast Sulawesi Ophiolite",
        "tier": "HIGH",
        "elevation_mean": 250,
        "elevation_max": 500,
        "elevation_min": 50,
        "slope_mean": 14,
        "roughness": 18,
        "terrain_class": "HILLY",
        "safety_score": 70,
        "safety_risks": "Moderate slope",
        "prob_score": 92,
        "prob_conf": "High",
        "worth_score": 95,
        "worth_est": "Rp 120M",
        "recommendation": "GO"
      }
    },
    {
      "type": "Feature",
      "geometry": { "type": "Point", "coordinates": [122.18, -3.61] },
      "properties": {
        "id": "tapunopaka",
        "name": "Tapunopaka",
        "province": "Sulawesi Tenggara",
        "type": "Laterite",
        "context": "Southeast Sulawesi Ophiolite",
        "tier": "LOW",
        "elevation_mean": 100,
        "elevation_max": 200,
        "elevation_min": 10,
        "slope_mean": 5,
        "roughness": 5,
        "terrain_class": "FLAT",
        "safety_score": 95,
        "safety_risks": "Very safe",
        "prob_score": 40,
        "prob_conf": "Low (Depleted)",
        "worth_score": 30,
        "worth_est": "Rp 50M",
        "recommendation": "NO-GO"
      }
    }
  ]
};
